### PR TITLE
fix Incorrect cursor position after css autocomplete

### PR DESCRIPTION
**Pull request by zqy233**
fix [#360](https://github.com/styled-components/vscode-styled-components/issues/360)

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Thanks @zqy233 will take a look soon

**Review by jasonwilliams — APPROVED** [review]

**Comment by jasonwilliams** [comment]
Thanks for your PR @zqy233

**Comment by GusPrado** [comment]
Unfortunately not completely fixed as recent discussion confirms on #360

**Comment by zqy233** [comment]
> Unfortunately not completely fixed as recent discussion confirms on #360

It seems to be OK on my Windows computer. I can't test it on MAC for the time being，Can you try to fix it？
the code in src/insertColonCommand.ts caused this problem，you can "git clone" this project and "npm i"，then "npx vsce package"，test the generated vsix file

image

**Pull request merged**
