### PR TITLE
Add support for TypeScript type parameters

### LINKED ISSUE #81: Support passing type parameters to styled function
TypeScript 2.9 will support passing type parameters to tagged template literals, i.e.

```tsx
styled<Props>`
  color: black;
`;
```

will become valid. The plugin should support this syntax and trigger the syntax highlighting.

### PR DESCRIPTION
**Pull request by antoinerousseau**
This updates #101 in an attempt to fix #81.

### CODE REVIEW

**Comment by julienp** [comment]
Thank you!

**Comment by JClackett** [comment]
WOOOOO

**Comment by declanelcocks** [comment]
Awaiting a new release 🙏

**Comment by antoinerousseau** [comment]
It's already been released in 0.0.26 yesterday: https://github.com/styled-components/vscode-styled-components/commit/e6a6d05a56281726d869f1378ff1893b7e707dfb

**Comment by deftomat** [comment]
🎉 Finally. Thanks @antoinerousseau

**Comment by pedrouid** [comment]
WOOHHOOO! 🎉🎉🎉 Thanks @antoinerousseau 🙌

**Comment by antoinerousseau** [comment]
You are welcome, but the main work was done by @sandervspl and @bensaufley so thanks to them ;)

**Comment by stramel** [comment]
@antoinerousseau Can you address the `css` tag as well?

```ts
const styles = css<{ error: string }>`
	color:${({ error }) => error ? 'red' : 'black'};
`
```

**Comment by antoinerousseau** [comment]
@stramel go ahead and open a PR :)

**Pull request merged**
