### PR TITLE
Add support for `@container` queries by updating the CSS language service

### PR DESCRIPTION
**Pull request by marvinroger**
This PR updates the CSS language service in order to support `@container` queries.

C.f. https://github.com/microsoft/vscode-css-languageservice/pull/365 and https://github.com/microsoft/vscode-css-languageservice/pull/371

The PR is ready to be published to npm 😉

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Thanks @marvinroger 
We will need to also update this here https://github.com/styled-components/typescript-styled-plugin/blob/main/package.json as that’s where the intellisense is handled.

Testing this is explained here: https://github.com/styled-components/vscode-styled-components/blob/main/CONTRIBUTING.md#intellisense

**Comment by marvinroger** [comment]
I messed up the link in the description but it's already done https://github.com/styled-components/typescript-styled-plugin/pull/19

This is why this PR is in draft

**Comment by jasonwilliams** [comment]
Ok great thanks, have you tested these changes locally?

**Comment by marvinroger** [comment]
I did not test locally, but I can confirm that `vscode-css-languageservice@6.2.11` does support container queries.
I'll let you test if you're OK with that 😉

**Comment by marvinroger** [comment]
Thanks, just updated the PR!

**Comment by macko911** [comment]
Thanks for doing this!
I tried to test this locally (built the extension and installed to VSCode) but it doesn't seem to have an effect - I still see the following warning.
image
This is the first time I'm building/installing a VSCode extension locally so it's probably just me not doing it right, but wanted to let you know. Hope your own test goes well. I can try and share some small reproduction later if it will be of any help.

**Comment by jasonwilliams** [comment]
Yeah I've tested this branch and I'm still getting the warning too, are we sure this has been fixed in the styled plugin?
@marvinroger If you could make a fixture and add it to this branch which we can all look at that would help.

Sorry I know you've [already](https://github.com/styled-components/typescript-styled-plugin/pull/19) done work in this repo but you may need to add a test [here](https://github.com/styled-components/typescript-styled-plugin/blob/main/e2e/tests/errors.js) so we can be sure this has been fixed in the plugin before we try adding it to the extension

**Pull request closed without merging**
