### PR TITLE
fix for space before <type>

### PR DESCRIPTION
**Pull request by mrGibi**
Fixes [this](https://github.com/styled-components/vscode-styled-components/issues/159#issuecomment-479934181)

### CODE REVIEW

**Comment by camsjams** [comment]
@julienp can this be merged? It fixes https://github.com/styled-components/vscode-styled-components/issues/159#issuecomment-479934181 and https://github.com/styled-components/vscode-styled-components/issues/209

**Comment by Sensiblemnd** [comment]
[data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUSExIWFRUXGBYVGBUXFhcVFxUVFRUWFxcXFRcYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OFxAPFS0dFx0rLS0tLSsrKy0tLS0rLSstLS0tKystLSstLS0tLS0tLTctLS0tLTctNy0tNzctLS0tLf/AABEIALEBHAMBIgACEQEDEQH/xAAcAAAABwEBAAAAAAAAAAAAAAAAAQIDBAUHBgj/xABVEAACAQMBBAQIBwoMBAUFAAABAgMABBESBQYhMQcTQVEUIjJhcYGRsyMkUnN0obEVMzQ1VHKTwdHSCBYlQkNEU2JjlLLCNoOS8GSFtMThRoKEosP/xAAXAQEBAQEAAAAAAAAAAAAAAAAAAQID/8QAHxEBAQEBAAMAAgMAAAAAAAAAAAERAhIhQQNREzFh/9oADAMBAAIRAxEAPwCk3h2xdC6uAt1cACeYACeUAAStgABuAHdVY+27v8suf8xN+/UreL8Lufn5vetVYyVoLbb93+WXP+Ym/epo7evPyy6/zM379MyR0grQPPty8/Lbr/Mzfv02u8F5n8Nuv8zN+/UaRqY0moq9l2/d6c+GXI4c/CJh/uqt/jZcfl91/mJ/3qi3knwTDzV6c3S2TbmxtCYIiTbwEkxoSSYlyTwqLa83JvXc9l/c+u5m/W1SDvVdL5V9cjPL4xMf91ehYdnbKvuuRbe3lMMjwSAwqrRyIcMoJUEfnLw7jWbbmbrRWm8lxaBQ8IgZ41kAfCv1TAeN3FmGefCiOFi3wuCceH3HH/Hm/W1PS72XCHD31wD3dfL+pq1bpz2dCmynZIY0brYuKoqnyu8CuR6E7ZJNpXAkRXAtgQGUMM9ZHx40FFs3fdw3j38+PPLMf11KbfN2Dlb6XSO3rZRjPpOa3bacez7dQ9wtrCpOkNIIkBbBOAWxxwCceavP/SEba520sds0TxStax5hKlDqZQwynDOTWca8kRt9Zfy+4/TTftpMO9tw5wt9cE93Xyj7Wr0z9xrb8nh/Rp+ysl6ftlxxLZXEcaIFkkjbSoXPWKCM4H9xvbVxnWf3e9N0nlX1wP8Any59gao0W+lx231165pv3q13oU3PtxZpfyxLJcTFnDOA3VIGZFEefJyBnI4+NjkK7iy2taXkt1aBRIbcqkyPGCnwgYgDVwYeKwPoqmsAj3tuBHqa9nx8rr5D/u403LvvJyF9P+lm/bVt0k7rQ2W17MQIEguJIXMXNVkWYK4UHkpBHDznswK3l9k2wBJghAAySY0wAOZPCphrzXHvlOTgX0/H/Gl/WatrLeK6zxupz6ZpD/uroOmnaWz5bS3W0ltXkF1GSIGiLaOrlBJ0cdOSv1VncVu000FsrFevmjhLDmFdgpP10sWVfba32dWCrezE9umWU8e7IOKj2m+0rHAvZ89xmlH2mt7g2fZbKtHdIViihQu7KoLtpHNm5ux89J2jsSx2rao8kKuk0avHIVCyIJFDKytzU8Rw9RzTFndYVLvfNG2l72ZSe+aU4HqNSF3z08toTN28ZZgPrNW/QTs1fDr+KdVlMSrHllDcY5GTIzn5NWv8IiwijsrcxxIhNwASqKpI6qThkCmF7/xy69IZCkeGSHP9+XhUOXfiViMXso/50i/aa9C2ux7fQvxeHyV/o07h5qqbXZOydoRM6W1tMmp4i3UqrKynDrkqHQ+cY7CKSYl61i43huufhc/6aT96j/jBd/lU/wCmk/eqNtfYngV/c2SkmOMo8RPPq5FDYz241Yz5jRnZ7dg4c89la2JIfbb90f63cfppP3qR937wf1u4P/Ok/eqvZOeOz6qIGqiyXeG6/K7j9NJ+9Tn3du/yu4/TSfvVUNRAkcqC4+7t1+V3H6aT96tb6J7qSSzdpJHkbrnGp2ZzjRHwyxzjifbWILL31tPQ4fiL/Pv/AKI6lGRbxj43c/Pz+9eq4LVrvGfjdz8/N71qqyaobdaYcVKNNMtBGC0krTrUlaKh3yfBt6DXqrc/8AtPo8Hulry/dr8DKccdOB+uvUG5/wCAWn0eD3S1kqk6P9357WbaUkyhRcXks0YDBiYyzFWOOWdXI8eFUFpIDvXMAeVmAfMfgj9hFUu2+lXaIuLqCCG2CwzywB31lsRuyg4Dc8AdmPNVf0TGRtuvJNMZpZLaR5JCMZcyIMADkAFAA4egcqGO36evxS/zsP8Aqqh6MdP3buiq6c2qkjBGT1keTxAq96e/xS/zsP8AqrmeiC6Em17lwQQbVeIOf6SPtqfT47jpT3Rl2lbRQwvGjJMspMmrSQqSLjxQc8XH11jO7m77wbwW9jL1TNFMkpaIFVJWEXC8wDw4dnfWx9K+9Nxs+2hlthHrknSE9aCVCskhzwYY4qOPprN+jC5mvN4ZLq46vrRA8jdV5AKrHAMcT2EdvbVRsu820RCLfj99uYIR5y7/APxXI9Ptn1myXf8AspYpPaxi/wD610W+270t54J1Tong93DdNqz4wi1eKMDmdVF0l2Qm2VeoRn4F3A88Q6xfrQUFH0Hbbjn2ZHCGHW2+qORO0AuzI2O4g8+9W7qb3r3Rv4Zbi92Pc9XLPpaeBkiYStGCFMTyKdJ8ZuBwCTzHAVn3R/0d380UG0rW+jt3YMBhW1YRyhDjGlgdHI5HKtb3M3pe4mubKdVFzaFVd489XKGHB0B4qeGCD5sHjgBgFzt29u7608OlLSw3MUfVtEkTR6pVJBCKvyRzr1LexF43Qc2VlGeWSCONY901bJRdo7LulUB5JlikPyurkiKEjtOGYZ7gB2VsF9KUjdxzVWYZ7wpIoPM+9HR/cbKWCSZ4JBJIIhoDagSCckso7qi284gltrsglYbiKRscToVgWx7Prp3eHfm72msK3Jt1SOTrAIwyvqGRggsaaIeTqLdCoM8yQ6mGQOsbTkjtHEVFj0xe20F9atGWEkE8ZGpG8pHHBlYe0Gsg3vTb2yY0EF4ZLGNVRXW3gLQxqAqiVShJwMDXkg444JxU/Yu7W09hwS3Au4ZraNWke1IcBgOJ6tiPg28/LvBrUNi7SjvLWOdVzHNGG0sAeDDirDiD2g1UY90AOzXt87uHZ0SRnAADNI7MTgcBxJ4VbfwkfwG3+kD3UlR+h7Zgttr7VgUYWM6UHcnWsUH/AEkVI/hI/gNv9IHupKDV7TyE/NX7BXNbjbAOzbaZZ5U8eea4ZgcIivpABZscgoyfPXS2nkJ+av2CuT6L9uTXdtM07a2jup4Q2FGUTSVBCgDhqx6qDJ96tsxXO17q4iYPCqRwrIvFXKqCxU8iM5GfQe2oz3rsBHnSM8x3U/v9Yx2+17qONQkciRS6BwUOwGogdmTk+uqUTY7amN83E+6aNQyJxJAy3nFV60gSEnNPLWpE6u0AaMUARSs1WRFa2XoaXFi/z7/6IqxrrK2bobbNi/z7/wCiKlGTbwp8bufn5vetUAJVjt9/jdz8/N71qguKBOmikiGKBFG3GgiNFSDFUnFEVoqNfD4vJ+afrr0xug48AtOI/B4O3/CWvNlw3AoeRGCKqvuXF8n6zWItjo7wjw/aPnvbj3r8a6TopCjbXA/1R+J+dWuKsIlQaUGBzPPianybKhmIMqZIwMgkcPVWdytzm2Y9I7Y2Zb3UfU3CJLGSDpblkcjzrPt1NlwWu8F3FbxrFGLOMhV5ZLx5NZ1b7pWbD70f+t/21a2+4lgRxiPf98f9tPOH8PTbdt7HtrtBHcxpKitrCtyDAEZ588MfbXM7t7v21rtW48HiSJBaWwwvItLNc5PE88Qr7KzO/wCj+0Cl0jIABJBd+IHHhxrndqbs2yeQMjnwZu7zmk7lS/jsbH0xb4z7Pht3t3AZ5cNlVbMaqSw48uJHGu8vI1kjeMkYdWQ8uTAg/bXk5dixYzp+s/tps7Ii+Sfaa2xjZugneeHwQbOkdY7iB5AEYgF1Z2fKfKIZmBA7ga7rZW68Fvd3V6jP1lzo1hiNC6B/MAAIzzOSfVXl64sYwAmjgO3jnj56deNnXS08zL8hpGK+yhY0XpZ3pgudpbPtoHEggnQyOpygd5IwEDDgSAhzjvxzBxuEmlgVJBBBBGeYPAivJP3PTTo08Ofr7899CPY0Pap9p/bRGsdL+6Gz7bZrzW9tFHIJIgHXOQC4B7ay9pmi6qZRqMEsc4Xv0Nqx5uVMnZMIwQhyPOamwDgaLj0XFeWm1rKRYpdcU0ZRtBAkj1rghgc6HGeRHtFOWy2uy7JI3lEcECBQ8jDJx6PKYnsA4k8BXmlbBQ2tC0bfKjYofqoprAMdUjPKRyMjl/toY0voZ2qLnau1LnksuHUHgdBkbRnz6dNS/wCEgwNjb4P9YHupKya5sI3OWXJwBkEjly5UgbMtwPI4/nN+2hj1laONCcR5K9vmFcD0JsPBLriPw65+yOsCk2fCP5p9p/bTcNhGWA08PSf21cR3XTHJ/LEuO2CH7K5WC5xwIyKhvapGxCjHrzQDUF3HKuMg0T3Cd9U5ei1iqLQXaUs7RQDkc1Ta6IPQWMt6DyGDW49CEurZ7n/xD+7irz7qrfOgY/ydJ9Ik93FSjMt4R8bufn5/etUVX4YqXvEPjdz8/N71qgUAY0YaiIoiKKFJ10ADQKUEW55+mmlqZNHxX103PEeR7Kxa3J607airG3kA5g1Ctl4VMhtA3PlXOu3E9JkW0lU8A2fSKtlu5BH1q9hxx45z2YqkksFVRgZI7T3d1dHu6wMRQ8cHP1YNZuOk36hbM21LMxVgxHIgAKBnvxxrmdrgrhe0DB9XCtJtrVYwcD199cDvXKOvdMeTjj36gG/XV4/tz79RXg+KPRUdeYqSgBUeio7DBrtXDk3c8cjuqKr1YGyLeMD2ZqsfnSHSYk/ClpLxqAr08rVWU0tTkPbUMKe+locVDU1I6S9Mlu40nrWqNFOKQ8eaUJO+grdtERbpQT56j2xw4qRcDJzTSp4wNaiEXDZYmmqNjk0TCqCoqOiNECnFhJGeymqWk5Ax2UCK37oF/F0n0iT3cVYATW/dAn4uk+kye7iqUZxvD+F3Pz83vWquU8asN4Pwu5+fm961V5NVS9dOqBio60qI4OKBwrTZenTGaT1JoG2cHGRy5UtACD7fXQMNMzQ6hg+qs9c63x34hE3dxqdavg1XquAOHLnTyPXKx35q5ussBinNiW82vIYKOIyMnGQcdvGoGguBh8cOI89SrG3k/wAQ+jkR6hWXSe3Wq44Lqzyz+s1mG1rgyTSOTnLHB8wOAPQABXb3UiwIzgtnGOLE5Y8sZriCgrf4p9cPzdfEZZSKAlzRSrRRtiuzgcS6YBhnsqAanTDI4VBIqGk07TRp5BQLjkxUoMDUMiiDYNBLJxQ1mo/WUaT1LBIVu8UrApoSU8uG58KikucVCkHbVksPDGajPH2VUV/KgTS5Y8GlMRiqGKSaM0RqgjUs2uQCKiVIhnxREdlxW/dAn4uk+kye7irBJedb50Cfi6T6RJ7uKorNt4B8bufn5vetVeKnbxN8bufn5vetVeDVDpNKUU1mlrQPiWktPTRHCkUD3X0gvxpIiPcaTIMAgjn9lZtWQmOXxvMaW8eOXsplh2jhUvZ2lmHWZ09uOdc7+3Xm/DSTlTy9lX+xrqZjhMDzk/sFRJlhR+DhgeQHE+sdnrpEN02pkC8NJY4OCVHYCOVZvt03PqVvHG0iIyFn4vkLyIH84LzrmRJWh9V1ZQAE9oJ4acKc6R6xTNxFDINUsSsRzOBn2863z1npws8vbPnNMV3Vxu5bnS0cblW5gM5A9nEe2o99unCSRHI0Zxn4QhlPHlyBH11vyjPi4/XwqMatb7Y8sZwV1dzIdan0EfYarpIyOYI9II+2qhk07ajLU2an2kXDPaaVZEafgabAqRcQknABJ7hT9tZKvGQ5/ug8B6T21FsQQDjODjlnHDPdmjABqfNtI9W0QHinAx2DByCo7/PVYTViWHSuKAc0EnxwPGnVuE7RRASUjtp0vnjSGuIx2ZphZck45UwOzpkVAYcan6s1HuU4ZpBHFEaAoGqCpWmk08z5qAiK3voH/Fz/AEiT3cVYOtbz0Ej+Tn+kSe7iqLWY7xJ8bufn5vevUJUqw2/nwu5+fm961Qccc1pBaMU6lN6c0tGoF6eHGhFOgIUrp/vZz7aRDrZygfSe48AaeKZGmVcdmoDGPSORrFbkS57ft7COP7arV4kxOcceBPYf2VYbOlKnqnOQRlG7CO6om2I8SZ76x9apwQ8CrDBXmO7AzVZImORq7tD1qf4gGPzl7vTVbJCeVBDZzz457xzqZZbTK8G8YYI84yMHBqK64oy3ADs7vTWkdg9+oVZFGFwEXUfJ4cc9+SOfopdtdOeWB28v1muNnEjeKBken7adgu5oV8WXgP5h8YfXUkXqfp288MjqdUjnlgFmxj0A4rmbu2IJ407Z77SqMPEjjAHAlD6udNTbchccUdfY315rWViVH6g8wTS5WkA8s+2kC+iHJyP/ALD+qm/CYyNPWAD81/1Cp7X0jTsT5QVvSoP186OOIAcV0+gk59R5e2pUYiH9L6xE7H1ZwBTM3Vc/hH9OIx9RJ+sVfYYkuMDgMDzdvpNVs7k+irbaUWlI5MjS4IwBp0kdnn4dtVMpFOTqGgaU2CKaakg1pnQJoBqI0BVQ66UuPhR5zSglQBDRvyp1QKZkPAmghCjNEKM1QmjFFQVqCQi1vXQX+L5PpEnu4qwDXW+9A34uk+kSe7irOLb6ZvvAPjdz8/N71qg4qdvAPjdz8/N71qr60hRodmaQKOoGWbUeA9JNWezr7SNHjMezTg+rB51AikHkhV9Jz+3jVpatp+T6hisVuHp7V5E1KuHXiAVCk944HB4VD2j48aydo4Gr60mIxwyp8/Lz8arttKqk4xh+OO5hz9tRpT2M2lsirq4j61dS+UOY+V6PPVDaxFjw4Adv/fM1Ypc6fJJJ7+VKRGFoS3EYHbn9lKaRIxheJ+Ucczw4UJZjzJyTzzUG6fINQIE7chUZ0c9nqpRYc+Rp8K5RWAGlsgH0HBzWp6N1He3ZV1HGPN2U3qp8xfLfh3DlUcgdhzWpWeoGunUamhEe6l6cVWEhZKf2eUeVUkyUJ44OD6jTEURV06xGCnjxBGoebNdId3Y5I+ttGJYH725DAkcwrADB8xrNvxuTPdczfzZ+CxgIzDzk5x+qoBWnZAcnOQcnOeee3NJzWpGbdplkpJGKccGm3NVCKFCjoH4uVSY6jR+TUhKytE9MzHsp1jTJHA1YiKKBoxRGqgjSaVRkUCK9A9Ap/k5/pEnu4q8/V6A6A/xdJ9Jk93FUozneFh4VcfPze9aq5jU7eIfG7n5+b3rVXZqqVQUUkCgD56Bp18bFWFnIMjIz3moczecYNOWzgDOePqrFajovDFAqFtC8jYAMmcHIyTn1ebzVWz3A4Y9Z51FeXPOs41qa90DwAAHcAABTPW5PGogaiDeerialTSZppuRpsv56Bcd9BBHE4NddsIoYdHA8WBHpJ5iuTTyvXUywvtDZ7CePo/bVqSukn2dC3AoMcuHAg+kVV7b2SkKqyljk4IOOHDPZU2TaagZwOXacA1B2ztASRKOHBgeBz2EVI1Vdc4CrjvpzZsihw2kcOXmPfUO4fxRk4qfsfZ5uAxjZesVciM85sHiE/vAdnbWs9My+0/bm0dSaO85PmxR7mbT6qXqSfEfiPM//AMgfVVI8mefPu7qSp0srZAIII7O2syemrddvvhsoSoZkX4ROLH5SAHOe8j7K4FjWnrcDIOQRy5+blXA7f2eIZmRTleDKf7rDI9nEeqtc1ixWg0l0oyaQ5rTJuhRigaB1TwqQlR4RmpmjhzrNawwwptzgUl5aYZh2mqgCgaAoZqgqMiipWqiE6a37oFH8nSfSJPdxVgWa33oG/F0n0iT3cVSjPN4YtV1cEf283vWqtMB7qs9vz4urn5+b3rVXeEmqouoNdx0TbsWl0l21zbRzMs6qpddRC9ShwPNkmuINzWm9BrZivT/4hfcx1Kin2Pu3s8wbaZ7aEm3nutBKjMUawgoF7gCGxV3sHdXZabJgvJ7KJtNpHPK2gF2xCHc+djxrLt6M+GbSAeRQ1zOGVZHRXA5B1U4bmeffWvH/AIZ/8s/9rUHP9IO4limz3v7KPqXREmGgsEljJGVdGJA8Vs5AByBXDbl2MU+0rOGZFkjdpdSMMq2IJCMjzEA1rm9n/D0n0OP3aVlXRwf5Wsfzpv8A00tFXHTNsC1tJbTwaBIdaXWrQunVpEOnPoyfbV+u59h/F/wnwSLrvueZes0jV1ng2rXnvzxqD/CDPwtj+Zd/ZBXUp/wz/wCWH/0tEU2wdz7BthpcPaQtL4G8hkKgsXEbHVnvyKib17q2Ozth65LSJrrqUi1soLm4lADMCe1SXYfmV2/RyFOx7QPjT4OurPLTg5z5sVyP8INJOotWz8CJZAw/xWhbqjnzASe2gstgbqbKTZdvd3FnDgWkM0shj1H7yrOxABJPM8Kyje6SykvHbZ6qtv1UY8WN4h1g16vFcA55ca3LYiwHYduLn7wbCES5LD4PwdNXFeI4Z5cawreFbNbuYbPbVa6YtOGkcaip14MhJ50I0Xo/3UsYtlfdK8t1uHMUlw3WKJQkSamVIkbxR4q578k8cUjpJ3UsTsv7pWlutu6pDMojURh45GTKSIvi+S+cjjleeKZ6J9/Io7dbG6VliTWIrllYwtGWJ0SsRhcZI1HxcDiRjix0tdHEcVvJe2ZKoi5kttTGPSSBriGfF05B0+TgcMYwQtt1d0tn2myxtG7t1uZGgFzIZEWTCsmtY4438VcBgPOeZ7oPS7uTax2LbQs4lt3TQWWMaUkjkYJ5A4KylwQw7iOPDHUbd/4bb6AnuFo+lL8Q3HzUPvIqB3d7cPZr2tu7WMBZoYmYlBksY1JJ8+apOjncCyME5uLWOVhd3SKXXJWOKTqgoPcDGfaa7LZF11dlZE8ilqn6REQfWwqZhYXiiTh1kszkd+oSSsf+phQZd/FWy/jF4L4LF4P4J1nU6fE6zVjVp78dtTOkWw2HZwTQNbQx3UlvK0AWB2Osq6xkMqlVOsDmRipn/wBVf/g/7qT0xw7LKSNdMBei2fwfx5VJ8sphUOk+PnnQZRubYJLfWUUyB0eQK6MMhvg2OCPSK1zpE3CsE2bdSQ2kUciRmRXRQGXqyHOD6FI9dZfuJ+MrDP8AbD3b16GvQsry2r+TJBxHmYuj/UVpRSbP6OtmrFGGsYGYIgYlASWCgEk9pzXC9DW6tlcwXTT2sUpS7kRS65KoEjwo8wya122udUkq/IKL6ygf7GFZ30C/g179Nl/0R0HL77JsVri0tbOGITLtCGK4VYZEHVh2jkRmZQrDVgYBOa0Da26WxoDCsljCOvlECaY/6RldhkjkMIePorgt9IdlLtG0Nmw8KO0o/CQHlbj12XyrnSPH7q1zeA2uu18J8rwheo8r8I6uTTnT/d18+HKgxrpE6P4YNoWMFrmKO9cxsmS3VFHj1umok+TJnHetaI+6+yLRra0NhE7XDPGjvEkrZjjaRmkkfxuIXs7T2CqXfpp/u9sgSKghDy9UVJLFsL1mvIGP6PGM9vGug362aZ7mxRbrwWRTcPHIAjMX0IuhVfgSVdz28AaDPN69xba12zs+ONAba6kOqBssqtGRqAz/ADDrU6TyIPZgDt95Ni7BsFR7q1gjV2Kqeod8kDJGEUkcK5reXZFxb7W2P4RfPd6ppNOuOOPq8dVnGjnnI5/Jrt+kSDZbRxfdMgIGPV5eVPH08eMRB5d9B5oGOOnydTaeBHi6jp4HlwxR4pNv5I/74Z4fVS60CxW+dA34uk+kSe7irBMVvfQR+LpPpEnu4qlGZbxfhdz8/P71qrqsN4W+N3PEff5vetVfnziqCArUug24RYrzUyr8YHMgf0MffWXMR3/XTMlpExyVUnvIGaCfvKQbzaBHEeEz8Rx7q2jYMEdxsOC2Myp1tjHEWyCV124UnTkZxnlWGwxIowoAHcMCmfAIP7NPYKmDaek7attb7IktRMjSNEkEUYZS7+SudIPIAEk8vqrLujmQDa1kWIADTcScf1eXma55oI1Y6VUejApMsSMMNg+nFRcb90j7r2u0I1kkuWRreOYoI3jGrWqkhtQOfvY5Y5moq3Kfxa061z9zCMahnPgvLHfWCCzj+Sv1UoWUfyV9goY3zdq5T+LyL1ihvAnGNQBB6pvPzpO98ke09gswZese3S4UZXUJEUSFQM8zhl9dYSLSL5CewVItrOEkDq0PEdg7xQ8XoDYMENxsW3tpJQqy2MMTEMoZQ1uqnGc4PpFYzvrsCKxvBbQzPLGYEly5RiGMkikAoAMYQe2ud8Eh+QnsFORRIvkhRnnjAoNl6Lr2G62O2zuuVZ1jnt3U+UqyGTQ4UnLLpdeI7Qal773MNhsQ2TzK8vgy2sa8A8raBHqVM5Cjn5gOdYfPbo/lBT9vtqTsKyi6wrpXiOB7RjuNDG1br3MO09iizSYLL4MttIDgvHIkYjLMmQSpK5B7Qah9NW2YotmPZK4eeRUARcFljiZXeRwPJXCYye0+msjvNjpqOtVI7D247OVX2xNmQxr4ijDjS3nHaD30PGtJ3h2pHFse1k1r8GdmufGGQEmt2P1A1a7W2mn3VsYxIunqbt28YYz8Cq5//esCutmQo7IY04HHIcuz6qaFlD/Zp7BVxGveEJ/GnVrXHgOM6hjOrvqx6Qt0LW9JununSSKBlURvEFIXU4zqUnmew9lYibCEjGhPYKjNs2P5K/VTBc7gXGdobPLEffQSTwGTE9bfebURdsW69Yul7S4HlDGpZYGGT6A1eeZbVcYOkju4U0LGL5K+wVcHo7dPaUb3G0m6xceFqoyw/mWlsnDjyyprl+gm4Rba81Oo+OyniwHDRHWM+Ax/JX2Cg1nH8hfYKmDVN79y7W2uYL6K5kZ5dowOyF4zGOtn1sQAoIAPea7Hf+6QybMw6nG0IScMOA6qfia88eCRfJX2Ch4JF8lfqpg2Lpg21HBf7HuNQZIpZ2fSdRCZtw5wO0LqPqrstuQW9wbTaHhUawWrSTlwQyOjRMvlA4GMg9vdXmtIY1OQFB82KQbSLOcL/wB+blTBuHSNco21diEOpAmmJIYEAHqcZNdHvtu1a7SSNJrhoxGxdTG8YJJXTx1A9lebRaxdy/VTkNhGxCqiEnlyH1mmA7q3CSyxqSwSWWMMcZKo7KCccM4ApspVpFsSVeCxgc+AaPkOJ/nUp9jzccoBjicunD0+NVFRpreegofye/0iT3cVY3LsiZcZTGeHlJz7udbR0ORmGxdZBpYzu2PK4FI8Z05xy5Uo6qXyj6T9tJNChUAoUKFAdFQoUBGhRUKgOhQoUUKMUKFEFRUKFAdGnOjoUCmpS0VCikvzpNChVQKFChQCioUKBVA0KFAVFQoUBUKFCgFA0KFAkUzaeQvoFChQOiptj5J9P6hR0KD/2Q==](url)

**Comment by julienp** [comment]
Merged and released, thanks.

**Comment by camsjams** [comment]
Thanks! This is now available after a reload in VSCode - brilliant!

**Comment by morikawa77** [comment]
Hi, I'm using v1.2.0 and I'm having this problem.

**Comment by jasonwilliams** [comment]
@morikawa77 could you raise a new issue?

**Comment by morikawa77** [comment]
> @morikawa77 could you raise a new issue?

Yes sir, thank you.

**Pull request merged**
